# uFCv2 xc7s25csga324-1
set_property  SEVERITY {Warning} [get_drc_checks UCIO-1]
set_property  SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property  BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

# I/O
set_property  PACKAGE_PIN E12           [get_ports "DIPSW[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[0]"]
set_property  PULLUP      true          [get_ports "DIPSW[0]"]
set_property  PACKAGE_PIN D12           [get_ports "DIPSW[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[1]"]
set_property  PULLUP      true          [get_ports "DIPSW[1]"]
set_property  PACKAGE_PIN B13           [get_ports "DIPSW[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[2]"]
set_property  PULLUP      true          [get_ports "DIPSW[2]"]
set_property  PACKAGE_PIN A13           [get_ports "DIPSW[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[3]"]
set_property  PULLUP      true          [get_ports "DIPSW[3]"]
set_property  PACKAGE_PIN B14           [get_ports "DIPSW[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[4]"]
set_property  PULLUP      true          [get_ports "DIPSW[4]"]
set_property  PACKAGE_PIN A14           [get_ports "DIPSW[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[5]"]
set_property  PULLUP      true          [get_ports "DIPSW[5]"]
set_property  PACKAGE_PIN B15           [get_ports "DIPSW[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[6]"]
set_property  PULLUP      true          [get_ports "DIPSW[6]"]
set_property  PACKAGE_PIN A15           [get_ports "DIPSW[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "DIPSW[7]"]
set_property  PULLUP      true          [get_ports "DIPSW[7]"]

set_property  PACKAGE_PIN M14           [get_ports "TESTPIN[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "TESTPIN[0]"]
set_property  PACKAGE_PIN N14           [get_ports "TESTPIN[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "TESTPIN[1]"]
set_property  PACKAGE_PIN C13           [get_ports "TESTPIN[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "TESTPIN[2]"]
set_property  PACKAGE_PIN C14           [get_ports "TESTPIN[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "TESTPIN[3]"]

set_property  PACKAGE_PIN U11           [get_ports "SYSLED[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "SYSLED[0]"]
set_property  PACKAGE_PIN V12           [get_ports "SYSLED[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "SYSLED[1]"]
set_property  PACKAGE_PIN R12           [get_ports "SYSLED[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "SYSLED[2]"]

# clk
set_property  PACKAGE_PIN F14           [get_ports "CLK_INOUT_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_INOUT_P"]
create_clock  -period 6.400 	-name OSCCLK  [get_ports "CLK_INOUT_P"]
# set_property  PACKAGE_PIN F15           [get_ports "CLK_INOUT_N"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_INOUT_N"]
set_property  PACKAGE_PIN N15           [get_ports "CLK_IN_P[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_P[0]"]
create_clock  -period 10.000 	-name REFCLK  [get_ports "CLK_IN_P[0]"]
# set_property  PACKAGE_PIN P16           [get_ports "CLK_IN_N[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_N[0]"]
set_property  PACKAGE_PIN D14           [get_ports "CLK_IN_P[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_P[1]"]
create_clock  -period 8.000 	-name WRCLK  	[get_ports "CLK_IN_P[1]"]
# set_property  PACKAGE_PIN D15           [get_ports "CLK_IN_N[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_N[1]"]

set_property  PACKAGE_PIN B16           [get_ports "CLK_OUT_P[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_P[0]"]
set_property  PACKAGE_PIN A16           [get_ports "CLK_OUT_N[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_N[0]"]
set_property  PACKAGE_PIN B17           [get_ports "CLK_OUT_P[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_P[1]"]
set_property  PACKAGE_PIN A17           [get_ports "CLK_OUT_N[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_N[1]"]
set_property  PACKAGE_PIN F18           [get_ports "CLK_OUT_P[2]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_P[2]"]
set_property  PACKAGE_PIN E18           [get_ports "CLK_OUT_N[2]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_N[2]"]
set_property  PACKAGE_PIN C17           [get_ports "CLK_OUT_P[3]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_P[3]"]
set_property  PACKAGE_PIN B18           [get_ports "CLK_OUT_N[3]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_N[3]"]

set_property  PACKAGE_PIN G16           [get_ports "FMC0_GTXCLK_M2C_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC0_GTXCLK_M2C_P"]
set_property  PACKAGE_PIN G17           [get_ports "FMC0_GTXCLK_M2C_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC0_GTXCLK_M2C_N"]
set_property  PACKAGE_PIN R14           [get_ports "FMC1_GTXCLK_M2C_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC1_GTXCLK_M2C_P"]
set_property  PACKAGE_PIN T14           [get_ports "FMC1_GTXCLK_M2C_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC1_GTXCLK_M2C_N"]
set_property  PACKAGE_PIN D18           [get_ports "FMC0_CLK_M2C_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC0_CLK_M2C_P"]
set_property  PACKAGE_PIN C18           [get_ports "FMC0_CLK_M2C_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC0_CLK_M2C_N"]
set_property  PACKAGE_PIN P14           [get_ports "FMC1_CLK_M2C_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC1_CLK_M2C_P"]
set_property  PACKAGE_PIN P15           [get_ports "FMC1_CLK_M2C_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC1_CLK_M2C_N"]
set_property  PACKAGE_PIN E16           [get_ports "FMC0_CLK_C2M_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC0_CLK_C2M_P"]
set_property  PACKAGE_PIN E17           [get_ports "FMC0_CLK_C2M_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC0_CLK_C2M_N"]
set_property  PACKAGE_PIN R15           [get_ports "FMC1_CLK_C2M_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC1_CLK_C2M_P"]
set_property  PACKAGE_PIN T15           [get_ports "FMC1_CLK_C2M_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC1_CLK_C2M_N"]

set_property  PACKAGE_PIN U17           [get_ports "FPGA_GTXCLK_P[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FPGA_GTXCLK_P[0]"]
set_property  PACKAGE_PIN U18           [get_ports "FPGA_GTXCLK_N[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FPGA_GTXCLK_N[0]"]
set_property  PACKAGE_PIN P17           [get_ports "FPGA_GTXCLK_P[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FPGA_GTXCLK_P[1]"]
set_property  PACKAGE_PIN P18           [get_ports "FPGA_GTXCLK_N[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FPGA_GTXCLK_N[1]"]
set_property  PACKAGE_PIN L17           [get_ports "FPGA_GTXCLK_P[2]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FPGA_GTXCLK_P[2]"]
set_property  PACKAGE_PIN L18           [get_ports "FPGA_GTXCLK_N[2]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FPGA_GTXCLK_N[2]"]

# IIC
set_property  PACKAGE_PIN V14           [get_ports "FPGA_SCL"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_SCL"]
set_property  PACKAGE_PIN V15           [get_ports "FPGA_SDA"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_SDA"]

# FPGA interface
set_property  PACKAGE_PIN P7            [get_ports "FPGA_RST_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FPGA_RST_B"]
set_property  PACKAGE_PIN J6            [get_ports "FPGA_PROG_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FPGA_PROG_B"]
set_property  PACKAGE_PIN L5            [get_ports "FPGA_DONE"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FPGA_DONE"]
set_property  PACKAGE_PIN M5            [get_ports "FPGA_INIT_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FPGA_INIT_B"]
set_property  PACKAGE_PIN N13           [get_ports "FPGA_RST_B_K7"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_RST_B_K7"]
set_property  PACKAGE_PIN L15           [get_ports "FPGA_PROG_B_K7"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_PROG_B_K7"]
set_property  PACKAGE_PIN L13           [get_ports "FPGA_DONE_K7"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_DONE_K7"]
set_property  PACKAGE_PIN L16           [get_ports "FPGA_INIT_B_K7"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_INIT_B_K7"]

set_property  PACKAGE_PIN K14           [get_ports "IO_P[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[0]"]
set_property  PACKAGE_PIN J15           [get_ports "IO_N[0]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[0]"]
set_property  PACKAGE_PIN H15           [get_ports "IO_P[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[1]"]
set_property  PACKAGE_PIN G15           [get_ports "IO_N[1]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[1]"]
set_property  PACKAGE_PIN H16           [get_ports "IO_P[2]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[2]"]
set_property  PACKAGE_PIN H17           [get_ports "IO_N[2]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[2]"]
set_property  PACKAGE_PIN D16           [get_ports "IO_P[3]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[3]"]
set_property  PACKAGE_PIN D17           [get_ports "IO_N[3]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[3]"]
set_property  PACKAGE_PIN K16           [get_ports "IO_P[4]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[4]"]
set_property  PACKAGE_PIN J16           [get_ports "IO_N[4]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[4]"]
set_property  PACKAGE_PIN M16           [get_ports "IO_P[5]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[5]"]
set_property  PACKAGE_PIN M17           [get_ports "IO_N[5]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[5]"]
set_property  PACKAGE_PIN R18           [get_ports "IO_P[6]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[6]"]
set_property  PACKAGE_PIN T18           [get_ports "IO_N[6]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[6]"]
set_property  PACKAGE_PIN U16           [get_ports "IO_P[7]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[7]"]
set_property  PACKAGE_PIN V17           [get_ports "IO_N[7]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[7]"]
set_property  PACKAGE_PIN M18           [get_ports "IO_P[8]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[8]"]
set_property  PACKAGE_PIN N18           [get_ports "IO_N[8]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[8]"]
set_property  PACKAGE_PIN R16           [get_ports "IO_P[9]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_P[9]"]
set_property  PACKAGE_PIN R17           [get_ports "IO_N[9]"]
set_property  IOSTANDARD  LVDS_25       [get_ports "IO_N[9]"]

# FLASH Interface
# set_property  PACKAGE_PIN K17           [get_ports "FLASH_D[0]"]
# set_property  IOSTANDARD  LVCMOS25      [get_ports "FLASH_D[0]"]
# set_property  PACKAGE_PIN K18           [get_ports "FLASH_D[1]"]
# set_property  IOSTANDARD  LVCMOS25      [get_ports "FLASH_D[1]"]
# set_property  PACKAGE_PIN L14           [get_ports "FLASH_D[2]"]
# set_property  IOSTANDARD  LVCMOS25      [get_ports "FLASH_D[2]"]
# set_property  PACKAGE_PIN M15           [get_ports "FLASH_D[3]"]
# set_property  IOSTANDARD  LVCMOS25      [get_ports "FLASH_D[3]"]
# set_property  PACKAGE_PIN M13           [get_ports "FLASH_CS_B"]
# set_property  IOSTANDARD  LVCMOS25      [get_ports "FLASH_CS_B"]

# MCU interface
set_property  PACKAGE_PIN R2            [get_ports "MCU_CLK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_CLK"]
create_clock  -period 125.000 	-name MCUCLK  [get_ports "MCU_CLK"]

set_property  PACKAGE_PIN K6            [get_ports "MCU_SPI1_SCK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI1_SCK"]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MCU_SPI1_SCK_IBUF]
set_property  PACKAGE_PIN L6            [get_ports "MCU_SPI1_NSS"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI1_NSS"]
set_property  PACKAGE_PIN L4            [get_ports "MCU_SPI1_MOSI"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI1_MOSI"]
set_property  PACKAGE_PIN K4            [get_ports "MCU_SPI1_MISO"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI1_MISO"]
set_property  PACKAGE_PIN K2            [get_ports "MCU_SPI2_SCK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI2_SCK"]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MCU_SPI2_SCK_IBUF]
set_property  PACKAGE_PIN K3            [get_ports "MCU_SPI2_NSS"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI2_NSS"]
set_property  PACKAGE_PIN L1            [get_ports "MCU_SPI2_MOSI"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI2_MOSI"]
set_property  PACKAGE_PIN K1            [get_ports "MCU_SPI2_MISO"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_SPI2_MISO"]
set_property  PACKAGE_PIN M6            [get_ports "MCU_UART_TX"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_UART_TX"]
set_property  PACKAGE_PIN M4            [get_ports "MCU_UART_RX"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MCU_UART_RX"]

# AMC
set_property  PACKAGE_PIN P2            [get_ports "AMC_TX[17]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX[17]"]
set_property  PACKAGE_PIN U1            [get_ports "AMC_TX[18]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX[18]"]
set_property  PACKAGE_PIN U3            [get_ports "AMC_TX[19]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX[19]"]
set_property  PACKAGE_PIN N3            [get_ports "AMC_TX[20]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX[20]"]

set_property  PACKAGE_PIN R1            [get_ports "AMC_RX[17]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX[17]"]
set_property  PACKAGE_PIN R3            [get_ports "AMC_RX[18]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX[18]"]
set_property  PACKAGE_PIN T2            [get_ports "AMC_RX[19]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX[19]"]
set_property  PACKAGE_PIN P1            [get_ports "AMC_RX[20]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX[20]"]

set_property  PACKAGE_PIN M2            [get_ports "AMC_TX_DE[17]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX_DE[17]"]
set_property  PACKAGE_PIN T1            [get_ports "AMC_TX_DE[18]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX_DE[18]"]
set_property  PACKAGE_PIN M1            [get_ports "AMC_TX_DE[19]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX_DE[19]"]
set_property  PACKAGE_PIN N4            [get_ports "AMC_TX_DE[20]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TX_DE[20]"]

set_property  PACKAGE_PIN N1            [get_ports "AMC_RX_DE[17]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX_DE[17]"]
set_property  PACKAGE_PIN N2            [get_ports "AMC_RX_DE[18]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX_DE[18]"]
set_property  PACKAGE_PIN U2            [get_ports "AMC_RX_DE[19]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX_DE[19]"]
set_property  PACKAGE_PIN N5            [get_ports "AMC_RX_DE[20]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_RX_DE[20]"]

# JTAG
set_property  PACKAGE_PIN T6            [get_ports "AMC_TCK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TCK"]
set_property  PACKAGE_PIN T4            [get_ports "AMC_TMS"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TMS"]
set_property  PACKAGE_PIN R5            [get_ports "AMC_TDI"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TDI"]
set_property  PACKAGE_PIN T5            [get_ports "AMC_TDO"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TDO"]
set_property  PACKAGE_PIN M3            [get_ports "AMC_TRST_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "AMC_TRST_B"]
set_property  PACKAGE_PIN R6            [get_ports "CON_TCK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "CON_TCK"]
set_property  PACKAGE_PIN R7            [get_ports "CON_TMS"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "CON_TMS"]
set_property  PACKAGE_PIN U6            [get_ports "CON_TDI"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "CON_TDI"]
set_property  PACKAGE_PIN U7            [get_ports "CON_TDO"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "CON_TDO"]
set_property  PACKAGE_PIN V3            [get_ports "FMC0_PRSNT_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC0_PRSNT_B"]
set_property  PACKAGE_PIN E14           [get_ports "FMC0_PRSNT_B_L"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC0_PRSNT_B_L"]
set_property  PACKAGE_PIN V7            [get_ports "FMC0_TCK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC0_TCK"]
set_property  PACKAGE_PIN P5            [get_ports "FMC0_TMS"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC0_TMS"]
set_property  PACKAGE_PIN P6            [get_ports "FMC0_TDI"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC0_TDI"]
set_property  PACKAGE_PIN V6            [get_ports "FMC0_TDO"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC0_TDO"]
set_property  PACKAGE_PIN V2            [get_ports "FMC1_PRSNT_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC1_PRSNT_B"]
set_property  PACKAGE_PIN E15           [get_ports "FMC1_PRSNT_B_L"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC1_PRSNT_B_L"]
set_property  PACKAGE_PIN R4            [get_ports "FMC1_TCK"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC1_TCK"]
set_property  PACKAGE_PIN V4            [get_ports "FMC1_TMS"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC1_TMS"]
set_property  PACKAGE_PIN V5            [get_ports "FMC1_TDI"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC1_TDI"]
set_property  PACKAGE_PIN T3            [get_ports "FMC1_TDO"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC1_TDO"]
set_property  PACKAGE_PIN T12           [get_ports "FPGA_TCK"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_TCK"]
set_property  PACKAGE_PIN V13           [get_ports "FPGA_TMS"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_TMS"]
set_property  PACKAGE_PIN U12           [get_ports "FPGA_TDI"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_TDI"]
set_property  PACKAGE_PIN T13           [get_ports "FPGA_TDO"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FPGA_TDO"]
